edition = "2021"
max_width = 100
tab_spaces = 4
hard_tabs = false
fn_params_layout = "Tall"
use_field_init_shorthand = true
use_try_shorthand = true
reorder_imports = true
reorder_modules = true
chain_width = 60
match_block_trailing_comma = true
