//! `rivet-relay init` — bootstrap a fresh deployment.
//!
//! Generates a cryptographically random 32-byte JWT secret (base64-encoded)
//! and writes a `.env` file populated with that secret plus sensible defaults
//! for every other configurable value. By default it refuses to overwrite an
//! existing file; pass `--force` to override.

use base64::Engine;
use clap::Args;
use rand_08::RngCore;
use std::path::{Path, PathBuf};

/// Arguments for the `init` subcommand.
#[derive(Debug, Args)]
pub struct InitArgs {
    /// Output path for the generated env file.
    #[arg(long, default_value = ".env")]
    pub output: PathBuf,

    /// Overwrite the output file if it already exists.
    #[arg(long)]
    pub force: bool,

    /// Database URL to write into the generated env file.
    #[arg(long, default_value = "postgres://rivet:rivet_dev@localhost/rivet")]
    pub database_url: String,

    /// Redis URL to write into the generated env file.
    #[arg(long, default_value = "redis://127.0.0.1:6379")]
    pub redis_url: String,

    /// Bind address (host:port) to write into the generated env file.
    #[arg(long, default_value = "0.0.0.0:8080")]
    pub bind_addr: String,
}

/// Errors emitted by the `init` subcommand.
#[derive(Debug, thiserror::Error)]
pub enum InitError {
    #[error("output file {0} already exists (use --force to overwrite)")]
    AlreadyExists(PathBuf),

    #[error("failed to generate random secret: {0}")]
    Rng(String),

    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
}

/// Generate a random 32-byte secret, base64-encoded (URL-safe, no padding).
///
/// The output is 43 ASCII characters, which exceeds the server's 32-character
/// minimum and provides 256 bits of entropy — appropriate for HS256 JWT signing.
pub fn generate_secret() -> Result<String, InitError> {
    let mut buf = [0u8; 32];
    rand_08::rngs::OsRng
        .try_fill_bytes(&mut buf)
        .map_err(|e| InitError::Rng(e.to_string()))?;
    Ok(base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(buf))
}

/// Render the full `.env` file body given the dynamic values.
fn render_env(secret: &str, database_url: &str, redis_url: &str, bind_addr: &str) -> String {
    format!(
        "# RivetLink Relay Server — generated by `rivet-relay init`\n\
         # DO NOT commit this file to version control.\n\
         \n\
         # Required\n\
         DATABASE_URL={database_url}\n\
         JWT_SECRET={secret}\n\
         \n\
         # Optional (defaults shown)\n\
         REDIS_URL={redis_url}\n\
         BIND_ADDR={bind_addr}\n\
         RUST_LOG=info\n\
         \n\
         # Token lifetimes (seconds)\n\
         ACCESS_TOKEN_EXPIRY_SECS=900\n\
         REFRESH_TOKEN_EXPIRY_SECS=604800\n\
         \n\
         # Login security\n\
         MAX_FAILED_LOGINS=5\n\
         LOCKOUT_DURATION_SECS=900\n\
         \n\
         # WebSocket\n\
         HEARTBEAT_INTERVAL_SECS=10\n\
         DISCONNECT_TIMEOUT_SECS=30\n\
         RECONNECT_GRACE_SECS=15\n",
    )
}

/// Write the env file to disk.
///
/// Refuses to clobber an existing file unless `force` is true. Returns the
/// resolved path that was actually written.
fn write_env_file(path: &Path, contents: &str, force: bool) -> Result<(), InitError> {
    if path.exists() && !force {
        return Err(InitError::AlreadyExists(path.to_path_buf()));
    }
    // The .env contains JWT_SECRET — write owner-only (0o600), not world-readable.
    rivetlink_core::secure_file::write_secret(path, contents.as_bytes())?;
    Ok(())
}

/// Entry point for `rivet-relay init`.
#[allow(clippy::needless_pass_by_value)] // clap subcommand handlers idiomatically take args by value
pub fn run(args: InitArgs) -> Result<(), InitError> {
    let secret = generate_secret()?;
    let body = render_env(
        &secret,
        &args.database_url,
        &args.redis_url,
        &args.bind_addr,
    );
    write_env_file(&args.output, &body, args.force)?;

    println!(
        "Wrote {} with a freshly generated JWT_SECRET.",
        args.output.display()
    );
    println!();
    println!("Next steps:");
    println!(
        "  1. Review {} and adjust DATABASE_URL / REDIS_URL if needed.",
        args.output.display()
    );
    println!("  2. Start dependencies:   docker compose -f docker/docker-compose.yml up -d");
    println!("  3. Run the server:       rivet-relay serve");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn tmp_path(name: &str) -> PathBuf {
        let mut p = std::env::temp_dir();
        let unique = format!(
            "rivetlink-init-test-{}-{name}",
            uuid::Uuid::now_v7().simple()
        );
        p.push(unique);
        p
    }

    #[test]
    fn generates_secret_with_enough_entropy() {
        let s = generate_secret().expect("rng must work");
        // 32 raw bytes → 43 chars in URL-safe base64 with no padding
        assert_eq!(s.len(), 43);
        assert!(s.len() >= 32, "must satisfy server JWT_SECRET min length");
        // base64 round-trip succeeds
        let decoded = base64::engine::general_purpose::URL_SAFE_NO_PAD
            .decode(&s)
            .expect("must be valid base64");
        assert_eq!(decoded.len(), 32);
    }

    #[test]
    fn secrets_are_unique() {
        let a = generate_secret().unwrap();
        let b = generate_secret().unwrap();
        assert_ne!(a, b, "two generated secrets must differ");
    }

    #[test]
    fn render_env_contains_all_keys() {
        let body = render_env("SECRET", "postgres://x", "redis://y", "0.0.0.0:9");
        assert!(body.contains("JWT_SECRET=SECRET"));
        assert!(body.contains("DATABASE_URL=postgres://x"));
        assert!(body.contains("REDIS_URL=redis://y"));
        assert!(body.contains("BIND_ADDR=0.0.0.0:9"));
        assert!(body.contains("RUST_LOG=info"));
        assert!(body.contains("ACCESS_TOKEN_EXPIRY_SECS=900"));
        assert!(body.contains("MAX_FAILED_LOGINS=5"));
        assert!(body.contains("HEARTBEAT_INTERVAL_SECS=10"));
    }

    #[test]
    fn writes_file_when_absent() {
        let path = tmp_path("absent");
        let _ = std::fs::remove_file(&path);

        write_env_file(&path, "hello", false).expect("must write");
        let read = std::fs::read_to_string(&path).unwrap();
        assert_eq!(read, "hello");

        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn refuses_to_overwrite_without_force() {
        let path = tmp_path("exists");
        std::fs::write(&path, "old").unwrap();

        let err = write_env_file(&path, "new", false).expect_err("must refuse");
        match err {
            InitError::AlreadyExists(p) => assert_eq!(p, path),
            other => panic!("wrong error variant: {other:?}"),
        }

        let still = std::fs::read_to_string(&path).unwrap();
        assert_eq!(still, "old", "original file must be untouched");

        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn force_overwrites_existing_file() {
        let path = tmp_path("force");
        std::fs::write(&path, "old").unwrap();

        write_env_file(&path, "new", true).expect("force must overwrite");
        let read = std::fs::read_to_string(&path).unwrap();
        assert_eq!(read, "new");

        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn run_creates_file_with_random_secret() {
        let path = tmp_path("run");
        let _ = std::fs::remove_file(&path);

        let args = InitArgs {
            output: path.clone(),
            force: false,
            database_url: "postgres://test".to_string(),
            redis_url: "redis://test".to_string(),
            bind_addr: "127.0.0.1:1".to_string(),
        };
        run(args).expect("run must succeed");

        let body = std::fs::read_to_string(&path).unwrap();
        assert!(body.contains("DATABASE_URL=postgres://test"));
        assert!(body.contains("REDIS_URL=redis://test"));
        assert!(body.contains("BIND_ADDR=127.0.0.1:1"));
        assert!(body.contains("JWT_SECRET="));

        // Extract the generated secret and confirm it meets the server's length floor.
        let line = body.lines().find(|l| l.starts_with("JWT_SECRET=")).unwrap();
        let secret = line.trim_start_matches("JWT_SECRET=");
        assert!(secret.len() >= 32);

        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn run_refuses_existing_file_without_force() {
        let path = tmp_path("existing");
        std::fs::write(&path, "do not touch").unwrap();

        let args = InitArgs {
            output: path.clone(),
            force: false,
            database_url: "x".into(),
            redis_url: "y".into(),
            bind_addr: "z".into(),
        };
        let err = run(args).expect_err("must refuse");
        assert!(matches!(err, InitError::AlreadyExists(_)));

        let still = std::fs::read_to_string(&path).unwrap();
        assert_eq!(still, "do not touch");

        let _ = std::fs::remove_file(&path);
    }
}
