[package]
name = "rivetlink-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rivetlink-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
bytes = { workspace = true }

[dev-dependencies]
proptest = "1"
uuid = { workspace = true }

[lints]
workspace = true
