[package]
name = "rivetlink-agent"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "rivet-agent"
path = "src/main.rs"

[lib]
name = "rivetlink_agent"
path = "src/lib.rs"

[dependencies]
rivetlink-core = { workspace = true }
rivetlink-protocol = { workspace = true }
rivetlink-crypto = { workspace = true }
rivetlink-sdk = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
clap = { workspace = true }
tokio-tungstenite = "0.24"
futures-util = "0.3"
async-trait = { workspace = true }
ed25519-dalek = { workspace = true }
x25519-dalek = { workspace = true }
rand_08 = { workspace = true }
base64 = { workspace = true }

[lints]
workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
ashpd = { version = "0.9", default-features = false, features = ["tokio"] }
url = "2"
png = "0.17"
